name: Sourcemeta Registry CD

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"

concurrency:
  group: registry-cd-${{ github.ref }}
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4

      # See https://docs.github.com/en/actions/publishing-packages/publishing-docker-images
      - uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        id: meta
        with:
          images: ghcr.io/${{ github.repository_owner }}/registry
      - uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        id: push
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - run: gh config set prompt disabled
        if: github.ref_type == 'tag'
        env:
          GH_TOKEN: ${{ github.token }}
      - run: gh release create ${{ github.ref_name }} --draft=false --title ${{ github.ref_name }} --target "$GITHUB_SHA" --generate-notes
        if: github.ref_type == 'tag'
        env:
          GH_TOKEN: ${{ github.token }}
